[package]
name = "iaue"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
fastrand = "2.1.0"
home = "0.5.9"
libloading = "0.8.5"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

wav_io = "0.1.14"

# terminal dependencies
crossterm = { version = "0.28.1", features = ["libc"], optional = true }
ratatui = { version = "0.28.0" }
tinyaudio = { version = "0.1.4", optional = true }

# sdl dependencies
sdl2 = { version = "0.37.0", optional = true, features = ["ttf"] }

[features]
default = ["dep:crossterm", "dep:tinyaudio", "dep:sdl2"]
sdl = ["dep:sdl2"]
