[package]
name = "iaue"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
itertools = "0.12.1"
pyo3 = { version = "0.21.2", features = ["auto-initialize"] }
ratatui = { version = "0.26.1", features = ["all-widgets"] }
rodio = "0.17.3"
